# Generated by Django 4.2.26 on 2025-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='original URL')),
                ('short_code', models.SlugField(unique=True, verbose_name='short code')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('last_access_time', models.DateTimeField(blank=True, null=True, verbose_name='last access time')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='access count')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'URL shortener',
                'verbose_name_plural': 'URL shorteners',
                'ordering': ['-created_time'],
            },
        ),
    ]
