# Generated by Django 4.2.26 on 2025-12-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0215_add_magazine_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The original URL to shorten.', max_length=2048, verbose_name='original URL')),
                ('suffix', models.CharField(db_index=True, help_text='The unique suffix for the shortened URL.', max_length=50, unique=True, verbose_name='suffix')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('last_edited_time', models.DateTimeField(auto_now=True, verbose_name='last edited time')),
                ('last_access_time', models.DateTimeField(blank=True, null=True, verbose_name='last access time')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='access count')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this shortener is active.', verbose_name='is active')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_shorteners', to='judge.profile', verbose_name='created by')),
            ],
            options={
                'verbose_name': 'URL shortener',
                'verbose_name_plural': 'URL shorteners',
                'ordering': ['-created_time'],
                'permissions': (('edit_all_urlshortener', 'Edit all URL shorteners'), ('view_all_urlshortener', 'View all URL shorteners')),
            },
        ),
    ]
