# Generated by Django 2.2.17 on 2021-04-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0114_remove_org_registrant'),
        ('judge', '0120_allow_py_cpp_files_in_custom_checker'),
    ]

    operations = [
    ]
