# Generated by Django 2.2.17 on 2021-04-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0122_allow_underscore_problemcode'),
        ('judge', '0115_contest_scoreboard_visibility'),
    ]

    operations = [
    ]
