# Generated by Django 2.2.20 on 2021-04-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0125_add_problem_pdf_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, verbose_name='problem body'),
        ),
    ]
