# Generated by Django 2.2.20 on 2021-04-30 09:48

from django.db import migrations, models

import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0126_allow_blank_desscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contribution_points',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, validators=[judge.models.problem.disallowed_characters_validator], verbose_name='problem body'),
        ),
    ]
