# Generated by Django 2.2.17 on 2021-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0126_allow_blank_desscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='performance_points',
            field=models.FloatField(default=0),
        ),
    ]
