# Generated by Django 2.2.20 on 2021-05-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0127_Add_contribution_points_and_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_contributive',
            field=models.IntegerField(default=False, verbose_name='is ticket contributive?'),
        ),
    ]
