# Generated by Django 2.2.17 on 2021-05-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0127_add_organization_performance_points'),
        ('judge', '0128_ticket_is_contributive'),
    ]

    operations = [
    ]
