# Generated by Django 2.2.22 on 2021-05-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0130_contest_virtual_count'),
        ('judge', '0118_convert_to_dates'),
    ]

    operations = [
    ]
