# Generated by Django 2.2.24 on 2021-06-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0119_hide_problem_authors'),
        ('judge', '0133_add_GeneralIssue_model'),
    ]

    operations = [
    ]
