# Generated by Django 2.2.24 on 2021-06-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0135_add_field_source_to_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='csv_ranking',
            field=models.TextField(
                blank=True,
                help_text='Official ranking exported from CMS in CSV format.',
                verbose_name='official ranking',
            ),
        ),
    ]
