# Generated by Django 2.2.20 on 2021-06-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0135_add_field_source_to_problem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'ordering': ('order',), 'verbose_name': 'contest problem', 'verbose_name_plural': 'contest problems'},
        ),
        migrations.AlterModelOptions(
            name='webauthncredential',
            options={'verbose_name': 'WebAuthn credential', 'verbose_name_plural': 'WebAuthn credentials'},
        ),
        migrations.AddField(
            model_name='problem',
            name='is_suggesting',
            field=models.BooleanField(default=False, help_text='Check if this problem is suggested and waiting for revision.', verbose_name='is suggesting'),
        ),
    ]
