# Generated by Django 2.2.20 on 2021-06-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0136_add_field_csv_ranking_to_contest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'ordering': ('order',), 'verbose_name': 'contest problem', 'verbose_name_plural': 'contest problems'},
        ),
        migrations.AlterModelOptions(
            name='webauthncredential',
            options={'verbose_name': 'WebAuthn credential', 'verbose_name_plural': 'WebAuthn credentials'},
        ),
        migrations.AddField(
            model_name='problem',
            name='suggesters',
            field=models.ManyToManyField(blank=True, help_text='Suggesters of this problem.', related_name='suggester', to='judge.Profile', verbose_name='Suggesters'),
        ),
    ]
