# Generated by Django 2.2.24 on 2021-07-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0139_add_can_upload_image_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='hashed_data',
            field=models.TextField(blank=True, null=True, verbose_name='Hashed data as json in the judges server'),
        ),
    ]
