# Generated by Django 2.2.20 on 2021-07-26 08:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0139_add_can_upload_image_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Tag group ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tag group name')),
            ],
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Tag group ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tag group name')),
            ],
        ),
        migrations.CreateModel(
            name='TagProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'Problem code must be ^[a-zA-Z0-9_]+$')], verbose_name='problem code')),
                ('name', models.CharField(max_length=100, verbose_name='problem name')),
                ('link', models.URLField(verbose_name='Problem URL')),
                ('tag', models.ManyToManyField(to='judge.Tag', verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='judge.TagGroup', verbose_name='Parent tag group'),
        ),
    ]
