# Generated by Django 2.2.24 on 2021-08-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0142_add_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='banned_tagging',
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_tagging',
            field=models.BooleanField(default=False, help_text='User will be allowed to tag problems.', verbose_name='Allow tagging'),
        ),
    ]
