# Generated by Django 2.2.24 on 2021-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0144_add_create_org_problem_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='file_only',
            field=models.BooleanField(default=False, help_text='If this language is submitted using file or not', verbose_name='File-only language'),
        ),
    ]
