# Generated by Django 2.2.24 on 2021-08-19 13:42

import django.db.models.deletion
from django.db import migrations, models

import judge.models.runtime


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0144_add_create_org_problem_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='file_only',
            field=models.BooleanField(default=False, help_text='If this language is submitted using file or not', verbose_name='File-only language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='key',
            field=models.CharField(help_text='The identifier for this language; the same as its executor id for judges.', max_length=10, unique=True, verbose_name='short identifier'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(default=judge.models.runtime.Language.get_default_language_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='judge.Language', verbose_name='preferred language'),
        ),
    ]
