# Generated by Django 2.2.24 on 2021-08-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0124_contest_show_short_display'),
        ('judge', '0145_alter_problem_pdf_url'),
    ]

    operations = [
    ]
