# Generated by Django 2.2.24 on 2021-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0147_allow_custom_grader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='common_name',
            field=models.CharField(help_text='Common name for the language. For example, the common name for C++03, C++11, and C++14 would be "C++".', max_length=20, verbose_name='common name'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='grader',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('interactive', 'Interactive'), ('signature', 'Function Signature Grading (IOI-style)'), ('output_only', 'Output Only'), ('custom_judge', 'Custom Grader')], max_length=30, verbose_name='Grader'),
        ),
    ]
