# Generated by Django 2.2.24 on 2021-08-27 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0152_contest_show_short_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_rank',
            field=models.CharField(choices=settings.VNOJ_DISPLAY_RANKS, default='user', max_length=10, verbose_name='display rank'),
        ),
    ]
