# Generated by Django 2.2.24 on 2021-09-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0153_new_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': (('edit_all_post', 'Edit all posts'), ('edit_organization_post', 'Edit organization posts')), 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='global_post',
            field=models.BooleanField(default=False, help_text='Display this blog post at the homepage.', verbose_name='global post'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_author_org', to='judge.Organization', verbose_name='organization'),
        ),
    ]
