# Generated by Django 2.2.24 on 2021-09-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0154_blog_post_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='announcement title')),
                ('description', models.TextField(verbose_name='announcement body')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='announcement timestamp')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Contest', verbose_name='announced_contest')),
            ],
        ),
    ]
