# Generated by Django 2.2.24 on 2021-09-20 05:21

from django.db import migrations, models


def set_existing_org_unlisted(apps, schema_editor):
    Organization = apps.get_model('judge', 'Organization')
    Organization.objects.update(is_unlisted=False)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0157_banned_judges_for_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_unlisted',
            field=models.BooleanField(default=True, help_text='Organization will not be listed', verbose_name='is unlisted organization?'),
        ),
        migrations.RunPython(set_existing_org_unlisted, migrations.RunPython.noop),
    ]
