# Generated by Django 2.2.24 on 2021-09-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0158_unlisted_org'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'permissions': (('organization_admin', 'Administer organizations'), ('edit_all_organization', 'Edit all organizations'), ('create_private_organization', 'Create private organizations'), ('change_open_organization', 'Change is_open field')), 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Allow joining organization', verbose_name='is open organization?'),
        ),
    ]
