# Generated by Django 2.2.24 on 2021-09-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0159_create_org'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('test_site', 'Shows in-progress development stuff'), ('totp', 'Edit TOTP settings'), ('can_upload_image', 'Can upload image directly to server via martor'), ('high_problem_timelimit', 'Can set high time limit for problem'), ('high_contest_time', 'Can set high contest time')), 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
    ]
