# Generated by Django 2.2.24 on 2021-10-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0161_add_create_mass_testcases_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='testcase_visibility_mode',
            field=models.CharField(choices=[('O', 'Visible for authors'), ('C', 'Visible if user is not in a contest'), ('A', 'Always visible')], default='O', max_length=1, verbose_name='Testcase visibility'),
        ),
    ]
