# Generated by Django 2.2.24 on 2021-11-03 11:26

from django.db import migrations, models

import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0162_add_testcase_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Show to banned user in login page.', null=True),
        ),
        migrations.AlterField(
            model_name='problemclarification',
            name='description',
            field=models.TextField(validators=[judge.models.problem.disallowed_characters_validator], verbose_name='clarification body'),
        ),
        migrations.AlterField(
            model_name='problemtranslation',
            name='description',
            field=models.TextField(validators=[judge.models.problem.disallowed_characters_validator], verbose_name='translated description'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='content',
            field=models.TextField(validators=[judge.models.problem.disallowed_characters_validator], verbose_name='editorial content'),
        ),
    ]
