# Generated by Django 2.2.24 on 2021-11-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0164_add_frozen_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='show_submission_list',
            field=models.BooleanField(default=True, help_text='Allow contestants to view submission list of others in contest time'),
        ),
    ]
