# Generated by Django 2.2.26 on 2022-03-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0172_contest_disallow_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='batch_policy',
            field=models.CharField(choices=[('min', 'Use min points in batch'), ('max', 'Use max points in batch')], default='min', max_length=3, verbose_name='Batch case scoring policy'),
        ),
    ]
