# Generated by Django 2.2.28 on 2022-06-17 12:45

import django.core.validators
from django.db import migrations, models
import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0175_model_blogvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='allow_judging',
            field=models.BooleanField(default=True, help_text='If disabled, submissions will be stored but not judged.', verbose_name='allow judging'),
        ),
    ]
