# Generated by Django 2.2.24 on 2022-03-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0175_add_java_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='submission_interval',
            field=models.IntegerField(default=0, help_text='Time in seconds between submissions per problem. 0 to disable.', verbose_name='submission interval'),
        ),
    ]
