# Generated by Django 2.2.26 on 2022-10-21 18:03

import django.core.validators
from django.db import migrations, models

import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0177_testcase_result_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdata',
            name='custom_checker',
            field=models.FileField(blank=True, null=True, storage=judge.utils.problem_data.ProblemDataStorage(), upload_to=judge.models.problem_data.problem_directory_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpp', 'py', 'pas', 'java'])], verbose_name='custom checker file'),
        ),
    ]
