# Generated by Django 2.2.28 on 2022-10-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0177_testcase_result_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registration_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='registration end time'),
        ),
        migrations.AddField(
            model_name='contest',
            name='registration_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='registration start time'),
        ),
    ]
