# Generated by Django 2.2.28 on 2023-01-06 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0173_auto_20220414_1339'),
        ('judge', '0179_add_ranking_access_code'),
    ]

    operations = [
    ]
