# Generated by Django 2.2.28 on 2022-12-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0181_contest_ranking_access_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='ranking_access_timer',
        ),
        migrations.AddField(
            model_name='contest',
            name='ranking_access_time',
            field=models.IntegerField(default=0, help_text='Set the time (in minutes) before the contest ends to disable the contest ranking.', verbose_name='ranking access time'),
        ),
    ]
