# Generated by Django 3.2.16 on 2023-01-31 15:53

import django.core.validators
from django.db import migrations, models

import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0182_remove_zombie_editorials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdata',
            name='custom_checker',
            field=models.FileField(blank=True, null=True, storage=judge.utils.problem_data.ProblemDataStorage(), upload_to=judge.models.problem_data.problem_directory_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpp', 'pas', 'java'])], verbose_name='custom checker file'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='custom_grader',
            field=models.FileField(blank=True, null=True, storage=judge.utils.problem_data.ProblemDataStorage(), upload_to=judge.models.problem_data.problem_directory_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpp'])], verbose_name='custom grader file'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='grader',
            field=models.CharField(choices=[('standard', 'Standard'), ('interactive', 'Interactive'), ('signature', 'Function Signature Grading (IOI-style)'), ('output_only', 'Output Only')], default='standard', max_length=30, verbose_name='Grader'),
        ),
    ]
