# Generated by Django 3.2.17 on 2023-05-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0191_submission_index_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registration_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='registration end time'),
        ),
        migrations.AddField(
            model_name='contest',
            name='registration_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='registration start time'),
        ),
    ]
