# Generated by Django 3.2.21 on 2023-09-15 06:42

from django.db import migrations, models


def make_slug_unique(apps, schema_editor):
    Organization = apps.get_model('judge', 'Organization')
    slugs = Organization.objects.values_list('slug', flat=True)
    slugs = set([i.lower() for i in slugs])
    for slug in slugs:
        orgs = Organization.objects.filter(slug=slug)
        if len(orgs) > 1:
            for org in orgs:
                org.slug += '-' + str(org.id)
                org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0192_add_registration_fields'),
    ]

    operations = [
        migrations.RunPython(make_slug_unique, migrations.RunPython.noop, atomic=True),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Organization name shown in URLs.', max_length=128, unique=True, verbose_name='organization slug'),
        ),
    ]
