# Generated by Django 3.2.21 on 2023-09-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0193_unique_organization_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('test_site', 'Shows in-progress development stuff'), ('totp', 'Edit TOTP settings'), ('can_upload_image', 'Can upload image directly to server via martor'), ('high_problem_timelimit', 'Can set high problem timelimit'), ('long_contest_duration', 'Can set long contest duration'), ('create_mass_testcases', 'Can create unlimitted number of testcases for a problem'), ('ban_user', 'Ban users')), 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
    ]
