# Generated by Django 3.2.21 on 2023-09-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0195_post_pin_global_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('view_all_user_comment', 'View all comments by a user'),), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
