# Generated by Django 3.2.21 on 2023-10-26 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('judge', '0197_org_slugs_begin_with_letter'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE judge_submission sub
                INNER JOIN (
                    SELECT MAX(stc.time) AS max_time, submission_id FROM judge_submissiontestcase stc GROUP BY stc.submission_id
                ) tc ON sub.id = tc.submission_id
            SET sub.time = tc.max_time
        """,
            """
            UPDATE judge_submission sub
                INNER JOIN (
                    SELECT SUM(stc.time) AS sum_time, submission_id FROM judge_submissiontestcase stc GROUP BY stc.submission_id
                ) tc ON sub.id = tc.submission_id
            SET sub.time = tc.sum_time
        """,
        ),
    ]
