# Generated by Django 3.2.21 on 2023-10-19 16:08

import django.core.validators
from django.db import migrations, models

import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0198_submission_max_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagelimit',
            name='time_limit',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(60)], verbose_name='time limit'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(db_index=True, help_text='The full name of the problem, as shown in the problem list.', max_length=100, validators=[judge.models.problem.disallowed_characters_validator], verbose_name='problem name'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(help_text='The time limit for this problem, in seconds. Fractional seconds (e.g. 1.5) are supported.', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(60)], verbose_name='time limit'),
        ),
    ]
