# Generated by Django 3.2.21 on 2023-12-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0199_change_min_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='show_submission_list',
            field=models.BooleanField(default=False, help_text='Allow contestants to view submission list of others in '
                                                               'contest time'),
        ),
    ]
