# Generated by Django 3.2.22 on 2023-10-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0200_add_ranking_stop_last_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.TextField(blank=True, null=True, verbose_name='uni group'),
        ),
    ]
