# Generated by Django 3.2.21 on 2023-12-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0200_update_show_submission_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='site_theme',
            field=models.CharField(choices=[('auto', 'Follow system default'), ('light', 'Light'), ('dark', 'Dark')],
                                   default='light', max_length=10, verbose_name='site theme'),
        ),
    ]
