# Generated by Django 3.2.23 on 2024-01-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0202_import_polygon_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscconfig',
            name='key',
            field=models.CharField(max_length=30, unique=True, verbose_name='key'),
        ),
    ]
