# Generated by Django 3.2.23 on 2024-01-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0202_import_polygon_package'),
    ]

    operations = [
        # add new column was_disqualifed to judge_profile table
        migrations.RunSQL(
            'ALTER TABLE judge_profile ADD COLUMN was_disqualified BOOLEAN NOT NULL DEFAULT FALSE',
        ),
    ]
