# Generated by Django 3.2.21 on 2024-03-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0202_import_polygon_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vnoj_points',
            field=models.IntegerField(default=0),
        ),
    ]
