# Generated by Django 3.2.23 on 2024-06-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0203_add_field_vnoj_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip_auth',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True,
                                               verbose_name='IP-based authentication'),
        ),
    ]
