# Generated by Django 3.2.23 on 2024-03-23 11:35

import django.db.models.deletion
from django.db import migrations, models


def set_type_voting_default(apps, schema_editor):
    Problem = apps.get_model('judge', 'Problem')
    db_alias = schema_editor.connection.alias
    Problem.objects.using(db_alias).filter(is_public=True, is_organization_private=False).update(allow_type_voting=True)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0203_add_field_vnoj_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='allow_type_voting',
            field=models.BooleanField(default=False, help_text='Allow public voting on problem types.'),
        ),
        migrations.RunPython(set_type_voting_default, migrations.RunPython.noop, atomic=True),
        migrations.CreateModel(
            name='ProblemTypeVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
                ('problem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problemtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile')),
            ],
            options={
                'unique_together': {('user', 'problem', 'problem_type')},
            },
        ),
    ]
