# Generated by Django 3.2.25 on 2024-06-05 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0203_add_field_vnoj_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.CharField(db_index=True, max_length=32, validators=[django.core.validators.RegexValidator('^\\w+:[a-z0-9A-Z_]+$', 'Page code must be ^\\w+:[a-z0-9A-Z_]+$')], verbose_name='associated page'),
        ),
    ]
