# Generated by Django 3.2.23 on 2024-03-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0204_problem_type_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='automated_type_voting',
            field=models.BooleanField(default=True, help_text='Automatically set problem types based on '
                                                              'a certain threshold of votes.'),
        ),
    ]
