# Generated by Django 3.2.19 on 2024-09-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0205_ip_based_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='available_credit',
            field=models.FloatField(default=0, help_text='Available credits'),
        ),
        migrations.AddField(
            model_name='organization',
            name='credit',
            field=models.FloatField(default=0, help_text='Total used credit this month'),
        ),
        migrations.AddField(
            model_name='organization',
            name='monthly_credit',
            field=models.FloatField(default=0, help_text='Total monthly free credit left'),
        ),
    ]
