# Generated by Django 3.2.19 on 2024-09-21 00:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0207_org_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_badge_name', models.CharField(blank=True, max_length=128, verbose_name='new badge name')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='request time')),
                ('state', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1, verbose_name='state')),
                ('desc', models.TextField(verbose_name='description')),
                ('cert', models.FileField(upload_to='certificates', validators=[django.core.validators.FileExtensionValidator(allowed_extensions={'pdf'})], verbose_name='Certificate')),
                ('badge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_requests', to='judge.badge', verbose_name='badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_requests', to='judge.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'badge request',
                'verbose_name_plural': 'badge requests',
            },
        ),
    ]
