# Generated by Django 3.2.25 on 2024-09-17 07:38

from django.db import migrations, models

import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0207_auto_20240917_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgerequest',
            name='new_badge_name',
            field=models.CharField(
                blank=True, max_length=128, verbose_name='new badge name'),
        ),
        migrations.AlterField(
            model_name='badgerequest',
            name='cert',
            field=models.FileField(upload_to='certificates/', validators=[
                                   judge.models.profile.validate_pdf], verbose_name='certificate'),
        ),
    ]
