# Generated by Django 3.2.25 on 2024-10-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0209_judge_add_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemExportKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('token', models.CharField(max_length=64, verbose_name='token')),
                ('remaining_uses', models.IntegerField(verbose_name='remaining uses')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
    ]
