# Generated by Django 3.2.25 on 2024-09-17 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0209_alter_badgerequest_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgerequest',
            name='cert',
            field=models.FileField(upload_to='certificates', validators=[django.core.validators.FileExtensionValidator(allowed_extensions={'pdf'})], verbose_name='Certificate'),
        ),
    ]
