# Generated by Django 3.2.25 on 2024-10-10 09:25

from django.db import migrations, models
from django.db.models import F


def populate_judge_code(apps, schema_editor):
    Problem = apps.get_model('judge', 'Problem')
    Problem.objects.update(judge_code=F('code'))


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0209_judge_add_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemExportKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('token', models.CharField(max_length=64, verbose_name='token')),
                ('remaining_uses', models.IntegerField(verbose_name='remaining uses')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='judge_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='judge code'),
        ),
        migrations.RunPython(populate_judge_code, migrations.RunPython.noop, atomic=True),
        migrations.AlterField(
            model_name='problem',
            name='judge_code',
            field=models.CharField(max_length=100, verbose_name='judge code'),
        ),
    ]
