# Generated by Django 3.2.19 on 2025-02-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0210_clarify_rate_all_desc'),
    ]

    operations = [
        # Thuc: https://b0uh.github.io/django-model-change-field-name-with-no-db-impact.html
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='organization',
                    old_name='monthly_credit',
                    new_name='free_credit',
                ),
                migrations.AlterField(
                    model_name='organization',
                    name='free_credit',
                    field=models.FloatField(db_column='monthly_credit', default=0, help_text='Free credits (reset monthly)'),
                ),
                migrations.RenameField(
                    model_name='organization',
                    old_name='available_credit',
                    new_name='paid_credit',
                ),
                migrations.AlterField(
                    model_name='organization',
                    name='paid_credit',
                    field=models.FloatField(db_column='available_credit', default=0, help_text='Paid credits'),
                ),
            ],
        ),
    ]
