# Generated by Django 3.2.25 on 2025-09-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0212_rename_credit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title_row',
            field=models.TextField(blank=True, verbose_name='title row'),
        ),
    ]
