# Generated by Django 4.2.21 on 2025-06-01 07:22

from django.db import migrations, models
import django.db.models.deletion
import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0212_rename_credit_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[judge.models.problem.disallowed_characters_validator], verbose_name='editorial content')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='judge.profile', verbose_name='author')),
                ('problem', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='editorial_proposals', to='judge.problem', verbose_name='associated problem')),
            ],
            options={
                'verbose_name': 'editorial proposal',
                'verbose_name_plural': 'editorial proposals',
                'permissions': (('see_editorial_proposal', 'See editorial proposals'),),
                'unique_together': {('problem', 'author')},
            },
        ),
    ]
