# Generated by Django 4.2.21 on 2025-06-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0212_rename_credit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='rate_disqualified',
            field=models.BooleanField(default=True, help_text='Rate users even if they are disqualified.', verbose_name='rate disqualified'),
        ),
    ]
