# Generated by Django 4.2.25 on 2025-10-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0211_add_user_group'),
        ('judge', '0213_add_rate_disqualified'),
    ]

    operations = [
    ]
