# Generated by Django 3.2.25 on 2025-09-22 19:09

import django.core.validators
from django.db import migrations, models
import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0213_add_problem_title_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='title_row',
            field=models.TextField(blank=True, verbose_name='title row'),
        ),
    ]
