# Generated by Django 4.2.21 on 2025-07-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0213_add_rate_disqualified'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Tên rút gọn')),
                ('long_url', models.URLField(max_length=2000, verbose_name='URL đích')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('click_count', models.IntegerField(default=0, verbose_name='Lượt click')),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortened_urls', to='judge.profile')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'URL rút gọn',
                'verbose_name_plural': 'URLs rút gọn',
                'permissions': (('create_url_shortener', 'Có thể tạo URL rút gọn'), ('view_all_url_stats', 'Xem thống kê tất cả URLs')),
            },
        ),
    ]
