# Generated by Django 4.2.21 on 2025-06-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0213_editorial_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialproposal',
            name='problem',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='editorial_proposals', to='judge.problem', verbose_name='associated problem'),
        ),
    ]
