# Generated by Django 4.2.26 on 2025-11-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0214_add_blog_tags'),
        ('judge', '0214_urlshortener'),
    ]

    operations = [
    ]
