# Generated by Django 4.2.23 on 2025-11-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0214_add_blog_tags'),
        ('judge', '0214_alter_contest_authors_alter_contest_curators_and_more'),
    ]

    operations = [
    ]
