# Generated by Django 3.2.25 on 2025-09-23 12:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0214_add_contest_title_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='title_row',
        ),
        migrations.AddField(
            model_name='contest',
            name='title_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.miscconfig', verbose_name='title row'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='title_row',
        ),
        migrations.AddField(
            model_name='problem',
            name='title_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.miscconfig', verbose_name='title row'),
        ),
    ]
