# Generated by Django 4.2.25 on 2025-11-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0214_add_blog_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': (('edit_all_post', 'Edit all posts'), ('edit_organization_post', 'Edit organization posts'), ('mark_global_post', 'Mark post as global'), ('pin_post', 'Pin post'), ('manage_magazine_post', 'Manage magazine blog posts')), 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
    ]
