# Generated by Django 4.2.27 on 2025-12-18 05:42

from django.db import migrations, models
import django.db.models.deletion


def migrate_organizations_to_organization(apps, schema_editor):  # noqa: ARG001
    """Migrate data from ManyToMany organizations to ForeignKey organization."""
    Problem = apps.get_model('judge', 'Problem')

    for problem in Problem.objects.all():
        # Get the first organization from the ManyToMany field
        first_org = problem.organizations.first()
        if first_org:
            problem.organization = first_org
            problem.save(update_fields=['organization'])


def reverse_migrate_organization_to_organizations(apps, schema_editor):  # noqa: ARG001
    """Reverse migration: copy ForeignKey organization back to ManyToMany organizations."""
    Problem = apps.get_model('judge', 'Problem')

    for problem in Problem.objects.all():
        if problem.organization:
            problem.organizations.add(problem.organization)

def migrate_contest_organizations_to_organization(apps, schema_editor):  # noqa: ARG001
    """Migrate data from ManyToMany organizations to ForeignKey organization."""
    Contest = apps.get_model('judge', 'Contest')

    for contest in Contest.objects.all():
        # Get the first organization from the ManyToMany field
        first_org = contest.organizations.first()
        if first_org:
            contest.organization = first_org
            contest.save(update_fields=['organization'])


def reverse_migrate_contest_organization_to_organizations(apps, schema_editor):  # noqa: ARG001
    """Reverse migration: copy ForeignKey organization back to ManyToMany organizations."""
    Contest = apps.get_model('judge', 'Contest')

    for contest in Contest.objects.all():
        if contest.organization:
            contest.organizations.add(contest.organization)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0215_add_magazine_permission'),
    ]

    operations = [
        # First, add the new organization field
        migrations.AddField(
            model_name='problem',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='If private, only this organization may see the problem.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.organization', verbose_name='organization'),
        ),
        # Migrate data from organizations to organization
        migrations.RunPython(
            migrate_organizations_to_organization,
            reverse_migrate_organization_to_organizations,
        ),
        # Finally, remove the old organizations field
        migrations.RemoveField(
            model_name='problem',
            name='organizations',
        ),
        # First, add the new organization field
        migrations.AddField(
            model_name='contest',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='If private, only this organization may see the contest', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.organization', verbose_name='organization'),
        ),
        # Migrate data from organizations to organization
        migrations.RunPython(
            migrate_contest_organizations_to_organization,
            reverse_migrate_contest_organization_to_organizations,
        ),
        # Finally, remove the old organizations field
        migrations.RemoveField(
            model_name='contest',
            name='organizations',
        ),
    ]
