# Generated by Django 4.2.27 on 2025-12-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0214_merge_0211_add_user_group_0213_add_rate_disqualified'),
        ('judge', '0215_add_magazine_permission'),
    ]

    operations = [
    ]
