# Generated by Django 4.2.27 on 2025-12-18 05:42

from django.db import migrations, models
import django.db.models.deletion

BATCH_SIZE = 1000

def migrate_organizations_to_organization(apps, schema_editor):  # noqa: ARG001
    """Migrate data from ManyToMany organizations to ForeignKey organization."""
    Problem = apps.get_model('judge', 'Problem')

    problems_to_update = []
    for problem in Problem.objects.prefetch_related('organizations').all():
        orgs = list(problem.organizations.all())
        if orgs:
            problem.organization = orgs[0]
            problems_to_update.append(problem)

        if len(problems_to_update) >= BATCH_SIZE:
            Problem.objects.bulk_update(problems_to_update, ['organization'], batch_size=BATCH_SIZE)
            problems_to_update = []

    if problems_to_update:
        Problem.objects.bulk_update(problems_to_update, ['organization'], batch_size=BATCH_SIZE)


def reverse_migrate_organization_to_organizations(apps, schema_editor):  # noqa: ARG001
    """Reverse migration: copy ForeignKey organization back to ManyToMany organizations."""
    Problem = apps.get_model('judge', 'Problem')

    for problem in Problem.objects.select_related('organization').all():
        if problem.organization:
            problem.organizations.add(problem.organization)

def migrate_contest_organizations_to_organization(apps, schema_editor):  # noqa: ARG001
    """Migrate data from ManyToMany organizations to ForeignKey organization."""
    Contest = apps.get_model('judge', 'Contest')

    contests_to_update = []
    for contest in Contest.objects.prefetch_related('organizations').all():
        orgs = list(contest.organizations.all())
        if orgs:
            contest.organization = orgs[0]
            contests_to_update.append(contest)

        if len(contests_to_update) >= BATCH_SIZE:
            Contest.objects.bulk_update(contests_to_update, ['organization'], batch_size=BATCH_SIZE)
            contests_to_update = []

    if contests_to_update:
        Contest.objects.bulk_update(contests_to_update, ['organization'], batch_size=BATCH_SIZE)


def reverse_migrate_contest_organization_to_organizations(apps, schema_editor):  # noqa: ARG001
    """Reverse migration: copy ForeignKey organization back to ManyToMany organizations."""
    Contest = apps.get_model('judge', 'Contest')

    for contest in Contest.objects.select_related('organization').all():
        if contest.organization:
            contest.organizations.add(contest.organization)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0215_add_magazine_permission'),
    ]

    operations = [
        # First, add the new organization field
        migrations.AddField(
            model_name='problem',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='If private, only this organization may see the problem.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.organization', verbose_name='organization'),
        ),
        # Migrate data from organizations to organization
        migrations.RunPython(
            migrate_organizations_to_organization,
            reverse_migrate_organization_to_organizations,
        ),
        # Finally, remove the old organizations field
        migrations.RemoveField(
            model_name='problem',
            name='organizations',
        ),
        # First, add the new organization field
        migrations.AddField(
            model_name='contest',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='If private, only this organization may see the contest', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.organization', verbose_name='organization'),
        ),
        # Migrate data from organizations to organization
        migrations.RunPython(
            migrate_contest_organizations_to_organization,
            reverse_migrate_contest_organization_to_organizations,
        ),
        # Finally, remove the old organizations field
        migrations.RemoveField(
            model_name='contest',
            name='organizations',
        ),
    ]
