# Generated by Django 4.2.27 on 2026-01-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0215_add_magazine_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscconfig',
            name='key',
            field=models.CharField(max_length=30, unique=True, verbose_name='key'),
        )
    ]
