# Generated by Django 4.2.25 on 2026-02-01 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0216_languagelimit_file_size_limit_alter_contest_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='file_size_limit',
            field=models.IntegerField(blank=True, default=0, help_text='Limit of file size (in KB) if allow submit via file', verbose_name='Limit of file size'),
        ),
        migrations.AlterField(
            model_name='languagelimit',
            name='file_size_limit',
            field=models.IntegerField(blank=True, help_text='File size limit in kilobytes (KB) for this problem and language. Leave blank to use the default language limit.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(102400)], verbose_name='file size limit'),
        ),
    ]
