# Generated by Django 4.2.27 on 2026-01-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0217_remove_problem_organizations_problem_organization_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['-end_time', 'key'], name='judge_conte_end_tim_c5e323_idx'),
        ),
    ]
