# Generated by Django 4.2.27 on 2026-02-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0218_contest_judge_conte_end_tim_c5e323_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='zipfile_size',
            field=models.BigIntegerField(default=0, help_text='Size of the test data zip file in bytes.', verbose_name='test data storage size'),
        ),
    ]
