# Generated by Django 4.2.25 on 2026-02-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0219_problemdata_zipfile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='submission_files_size',
            field=models.BigIntegerField(default=0, help_text='Size of all submission files in bytes.', verbose_name='submission files storage size'),
        ),
    ]
