# Generated by Django 4.2.26 on 2026-03-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0219_problemdata_zipfile_size_alter_contest_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='deleted at'),
        ),
    ]
