# Generated by Django 4.2.27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0219_alter_problem_options_alter_contest_authors_and_more'),
        ('judge', '0219_problemdata_zipfile_size_alter_contest_authors_and_more'),
    ]

    operations = [
    ]
