# Generated by Django 4.2.26 on 2026-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0220_problem_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='publicly visible'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_public', 'is_organization_private', '-date'], name='judge_probl_is_publ_b00d80_idx'),
        ),
    ]
