# Generated by Django 4.2.27 on 2026-05-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0221_problem_compound_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='terms',
            field=models.TextField(blank=True, verbose_name='terms'),
        ),
    ]
