# Generated by Django 4.2.25 on 2026-04-26 16:29

from django.db import migrations, models
import judge.models.user_file


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0221_alter_contest_authors_alter_contest_curators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileusage',
            name='contest_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='contest ID'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='storage_scope',
            field=models.CharField(choices=[('problem', 'Problem editor'), ('contest', 'Contest editor'), ('martor', 'Martor editor')], db_index=True, default='martor', max_length=20, verbose_name='storage scope'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(storage=judge.models.user_file.UserFileStorage(), upload_to=judge.models.user_file.user_file_directory, verbose_name='file'),
        ),
        migrations.AddIndex(
            model_name='fileusage',
            index=models.Index(fields=['contest_id', 'usage_type'], name='judge_fileu_contest_6661a5_idx'),
        ),
        migrations.AddIndex(
            model_name='userfile',
            index=models.Index(fields=['storage_scope', '-uploaded_at'], name='judge_userf_storage_f87e05_idx'),
        ),
    ]
