# Generated by Django 4.2.30 on 2026-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0222_add_contest_terms'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-id'], name='judge_submi_user_id_52a3e2_idx'),
        ),
    ]
