# Generated by Django 4.2.25 on 2026-04-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0221_problem_compound_index'),
        ('judge', '0222_fileusage_contest_id_userfile_storage_scope_and_more'),
    ]

    operations = [
    ]
