# Generated by Django 4.2.27 on 2026-05-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0223_submission_judge_submi_user_id_52a3e2_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='action',
            field=models.CharField(blank=True, choices=[('open', 'opened'), ('close', 'closed')], max_length=10, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='message body'),
        ),
    ]
