# Generated by Django 4.2.30 on 2026-06-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0225_add_pac_result'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'date'], name='judge_submi_user_id_a309f7_idx'),
        ),
    ]
