# Generated by Django 4.2.30 on 2026-06-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0225_add_pac_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('added_problems', models.IntegerField(default=0, help_text='Number of additional problems allowed above the default limit.', verbose_name='additional problems')),
                ('added_storage', models.BigIntegerField(default=0, help_text='Additional storage allowed above the default limit, in bytes.', verbose_name='additional storage (bytes)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='judge.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'organization quota',
                'verbose_name_plural': 'organization quotas',
                'ordering': ['start_date'],
            },
        ),
    ]
