# Generated by Django 4.2.30 on 2026-06-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0228_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='judge_notif_recipie_9180e7_idx',
            old_name='judge_notif_recip_i_0f60e0_idx',
        ),
    ]
