# Generated by Django 4.2.30 on 2026-07-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0230_alter_problem_options_remove_problem_suggester'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='replay_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
