# Generated by Django 4.2.30 on 2026-06-25 08:38
import uuid

import django.db.models.deletion
from django.db import migrations, models

import judge.models.user_upload


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0231_contest_replay_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file_scope', models.CharField(choices=[('martor', 'Martor Image'), ('attachment', 'Attachment')], db_index=True, default='attachment', max_length=32, verbose_name='file scope')),
                ('file', models.FileField(storage=judge.models.user_upload.UserUploadStorage(), upload_to=judge.models.user_upload.user_upload_directory, verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('size', models.BigIntegerField(default=0, verbose_name='file size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='judge.profile', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'user upload',
                'verbose_name_plural': 'user uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='display name')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='judge.userupload', verbose_name='file')),
            ],
            options={
                'verbose_name': 'file attachment',
                'verbose_name_plural': 'file attachments',
            },
        ),
    ]
