# Generated by Django 4.2.30 on 2026-07-09 16:49

from django.db import migrations, models
import django.db.models.deletion
import judge.models.user_file
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0231_contest_replay_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(storage=judge.models.user_file.UserFileStorage(), upload_to=judge.models.user_file.user_file_directory, verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('storage_scope', models.CharField(choices=[('problem', 'Problem'), ('contest', 'Contest'), ('user', 'User upload')], db_index=True, default='user', max_length=20, verbose_name='storage scope')),
                ('size', models.BigIntegerField(default=0, verbose_name='file size in bytes')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('last_accessed', models.DateTimeField(auto_now_add=True, verbose_name='last accessed')),
                ('access_count', models.IntegerField(default=0, verbose_name='access count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='judge.profile', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'user file',
                'verbose_name_plural': 'user files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('problem_checker', 'Problem - Checker'), ('problem_grader', 'Problem - Grader'), ('problem_header', 'Problem - Header'), ('problem_data', 'Problem - Test Data'), ('problem_statement_attachment', 'Problem - Statement Attachment'), ('submission_attachment', 'Submission - Attachment'), ('markdown_content', 'Markdown - Content Image'), ('library_personal', 'Library - Personal'), ('library_shared', 'Library - Shared'), ('other', 'Other')], default='other', max_length=50, verbose_name='usage type')),
                ('problem_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='problem ID')),
                ('contest_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='contest ID')),
                ('submission_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='submission ID')),
                ('context_description', models.CharField(blank=True, max_length=255, verbose_name='context description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='judge.userfile', verbose_name='file')),
            ],
            options={
                'verbose_name': 'file usage',
                'verbose_name_plural': 'file usages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userfile',
            index=models.Index(fields=['user', '-uploaded_at'], name='judge_userf_user_id_bcab28_idx'),
        ),
        migrations.AddIndex(
            model_name='userfile',
            index=models.Index(fields=['storage_scope', '-uploaded_at'], name='judge_userf_storage_f87e05_idx'),
        ),
        migrations.AddIndex(
            model_name='fileusage',
            index=models.Index(fields=['file', 'usage_type'], name='judge_fileu_file_id_349b69_idx'),
        ),
        migrations.AddIndex(
            model_name='fileusage',
            index=models.Index(fields=['problem_id', 'usage_type'], name='judge_fileu_problem_db512d_idx'),
        ),
        migrations.AddIndex(
            model_name='fileusage',
            index=models.Index(fields=['contest_id', 'usage_type'], name='judge_fileu_contest_6661a5_idx'),
        ),
        migrations.AddIndex(
            model_name='fileusage',
            index=models.Index(fields=['submission_id'], name='judge_fileu_submiss_f0b8a9_idx'),
        ),
    ]
