# Generated by Django 4.2.30 on 2026-08-09 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0231_contest_replay_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='problem tag')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_tags', to='judge.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'organization problem tag',
                'verbose_name_plural': 'organization problem tags',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text="Tags from this problem's organization.", related_name='problems', to='judge.organizationproblemtag', verbose_name='problem tags'),
        ),
    ]
