# Generated by Django 4.2.30 on 2026-07-09 16:49

from django.db import migrations, models
import django.db.models.deletion
import judge.models.user_file
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0231_contest_replay_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(storage=judge.models.user_file.UserFileStorage(), upload_to=judge.models.user_file.user_file_directory, verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('size', models.BigIntegerField(default=0, verbose_name='file size in bytes')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='judge.profile', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'user file',
                'verbose_name_plural': 'user files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
