# Generated by Django 4.2.30 on 2026-08-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_organization_problem_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notice',
            field=models.TextField(blank=True, default='', help_text='Warning banner shown to the administrators of this organization.', verbose_name='organization notice'),
        ),
    ]
