# Generated by Django 4.2.30 on 2026-09-21 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0236_judge_storages'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='state')),
                ('name', models.CharField(blank=True, help_text='Required when registering a new organization.', max_length=128, verbose_name='organization title')),
                ('slug', models.SlugField(blank=True, help_text='Organization name shown in URLs. Required when registering a new organization.', max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Z]', 'Organization slugs must begin with a letter.')], verbose_name='organization slug')),
                ('short_name', models.CharField(blank=True, help_text='Displayed beside user name during contests. Required when registering a new organization.', max_length=20, verbose_name='short name')),
                ('about', models.TextField(blank=True, help_text='Required when registering a new organization.', verbose_name='organization description')),
                ('applicant_name', models.CharField(help_text='Your real name, as shown on the proof you upload.', max_length=128, verbose_name='full name')),
                ('facebook', models.CharField(help_text='Link to the Facebook account we should contact you through.', max_length=256, verbose_name='Facebook')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, help_text='Optional.', max_length=32, verbose_name='phone number')),
                ('reason', models.TextField(blank=True, help_text='Required when registering a new organization.', verbose_name='reason')),
                ('proof_files', models.JSONField(blank=True, default=list, verbose_name='proof')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='request time')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='review time')),
                ('review_note', models.TextField(blank=True, verbose_name='review note')),
                ('organization', models.ForeignKey(blank=True, help_text='Leave empty to register a new organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_forms', to='judge.organization', verbose_name='organization')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_organization_registration_forms', to='judge.profile', verbose_name='reviewer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_registration_forms', to='judge.profile', verbose_name='applicant')),
            ],
            options={
                'verbose_name': 'organization registration form',
                'verbose_name_plural': 'organization registration forms',
                'ordering': ('-time',),
            },
        ),
    ]
