# Generated by Django 4.2.30 on 2026-09-22 12:10

from django.db import migrations


def remove_tag_comments(apps, schema_editor):
    apps.get_model('judge', 'CommentLock').objects.filter(page__startswith='t:').delete()
    apps.get_model('judge', 'Comment').objects.filter(page__startswith='t:').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0236_judge_storages'),
    ]

    operations = [
        migrations.RunPython(remove_tag_comments, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='tagdata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tagdata',
            name='assigner',
        ),
        migrations.RemoveField(
            model_name='tagdata',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='tagdata',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagproblem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='allow_tagging',
        ),
        migrations.DeleteModel(name='Tag'),
        migrations.DeleteModel(name='TagData'),
        migrations.DeleteModel(name='TagGroup'),
        migrations.DeleteModel(name='TagProblem'),
    ]
