# Generated by Django 4.2.30 on 2026-10-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0236_judge_storages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='hide_problem_authors',
            field=models.BooleanField(default=True, help_text='Whether problem authors should be hidden by default.', verbose_name='hide problem authors'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='hide_problem_tags',
            field=models.BooleanField(default=True, help_text='Whether problem tags should be hidden by default.', verbose_name='hide problem tags'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='scoreboard_cache_timeout',
            field=models.PositiveIntegerField(default=3, help_text='How long should the scoreboard be cached. Set to 0 to disable caching.', verbose_name='scoreboard cache timeout'),
        ),
    ]
