# Generated by Django 4.2.30 on 2026-10-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0237_contest_official_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('see_private_contest', 'See private contests'), ('edit_own_contest', 'Edit own contests'), ('edit_all_contest', 'Edit all contests'), ('clone_contest', 'Clone contest'), ('moss_contest', 'MOSS contest'), ('contest_rating', 'Rate contests'), ('contest_access_code', 'Contest access codes'), ('create_private_contest', 'Create private contests'), ('change_contest_visibility', 'Change contest visibility'), ('contest_problem_label', 'Edit contest problem label script'), ('lock_contest', 'Change lock status of contest'), ('view_contest_balloons', 'View contest balloons')), 'verbose_name': 'contest', 'verbose_name_plural': 'contests'},
        ),
    ]
