# Generated by Django 4.2.30 on 2026-10-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0238_contest_balloons_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.CharField(blank=True, help_text='Group used to filter contest rankings, e.g. university group.', max_length=100, verbose_name='ranking group'),
        ),
    ]
